version: "3"

services:
  sni_api:
    build: "."
    tty: true
    command: yarn start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "7000:3000"
      - "7001:3001"
    env_file:
      - .env
networks:
  default:
    external:
      name: sni